import { useEffect, useMemo, useRef, useState } from "react";

import { Reveal } from "@/components/Reveal";
import { useSectionProgress } from "@/hooks/useScrollSignal";
import { buildSimulation, cagr } from "@/lib/marketData";

const W = 1000;
const H = 380;
const sim = buildSimulation();

function pathFor(key: "rule" | "hold") {
  const maxLog = Math.log10(Math.max(...sim.map((p) => p.rule)));
  return sim
    .map((p, i) => {
      const x = (i / (sim.length - 1)) * W;
      const y = H - (Math.log10(p[key]) / maxLog) * (H - 20) - 10;
      return `${i === 0 ? "M" : "L"}${x.toFixed(1)} ${y.toFixed(1)}`;
    })
    .join(" ");
}

export function Simulation() {
  const ref = useRef<HTMLDivElement>(null);
  const progress = useSectionProgress(ref);
  const [isMobile, setIsMobile] = useState(false);
  useEffect(() => {
    const media = window.matchMedia("(max-width: 767px)");
    const update = () => setIsMobile(media.matches);
    update();
    media.addEventListener("change", update);
    return () => media.removeEventListener("change", update);
  }, []);
  const paths = useMemo(() => ({ rule: pathFor("rule"), hold: pathFor("hold") }), []);

  const eased = isMobile ? 1 : Math.max(0, Math.min(1, (progress - 0.2) / 0.42));
  const idx = Math.max(1, Math.round(eased * (sim.length - 1)));
  const point = sim[idx];
  const years = point.year - 1950 || 1;

  return (
    <section ref={ref} className="relative px-6 py-24 md:min-h-[300vh] md:px-16 md:py-0">
      <div className="mx-auto max-w-6xl md:sticky md:top-0 md:flex md:min-h-screen md:flex-col md:justify-center md:py-8">
        <Reveal>
          <p className="label-mono">04 — Illustrative simulation</p>
        </Reveal>
        <Reveal delay={0.1}>
          <h2 className="display-lg mt-6 max-w-3xl">
            What would a long-view simulation look like?
          </h2>
        </Reveal>

        <div className="mt-10 grid gap-8 md:grid-cols-[1fr_auto] md:items-end">
          <div className="border-border/70 bg-card/40 rounded-md border p-6 backdrop-blur-sm">
            <svg viewBox={`0 0 ${W} ${H}`} className="h-[250px] w-full md:h-[min(38vh,380px)]">
              <defs>
                <clipPath id="sim-clip">
                  <rect x="0" y="0" width={W * eased} height={H} />
                </clipPath>
              </defs>
              {[0.25, 0.5, 0.75].map((g) => (
                <line
                  key={g}
                  x1="0"
                  x2={W}
                  y1={H * g}
                  y2={H * g}
                  stroke="currentColor"
                  className="text-border"
                  strokeWidth="1"
                />
              ))}
              <g clipPath="url(#sim-clip)">
                <path
                  d={paths.hold}
                  fill="none"
                  stroke="currentColor"
                  className="text-noise"
                  strokeWidth="1.5"
                  vectorEffect="non-scaling-stroke"
                />
                <path
                  d={paths.rule}
                  fill="none"
                  stroke="currentColor"
                  className="text-signal"
                  strokeWidth="2"
                  vectorEffect="non-scaling-stroke"
                />
              </g>
            </svg>
            <div className="data mt-4 flex flex-wrap gap-6 text-[0.7rem]">
              <span className="text-signal">▬ 3-month-rule rotation</span>
              <span className="text-noise">▬ buy &amp; hold benchmark</span>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-5 md:w-64 md:grid-cols-1 md:gap-5">
            <div>
              <p className="label-mono">Year</p>
              <p className="data text-signal text-glow mt-2 text-4xl">{point.year}</p>
            </div>
            <div>
              <p className="label-mono">Sample rule — annualised</p>
              <p className="data text-signal mt-2 text-3xl">
                {cagr(point.rule, years).toFixed(1)}%
              </p>
            </div>
            <div>
              <p className="label-mono">Sample benchmark — annualised</p>
              <p className="data text-noise mt-2 text-3xl">{cagr(point.hold, years).toFixed(1)}%</p>
            </div>
            <div>
              <p className="label-mono">Growth of 1 unit</p>
              <p className="data mt-2 text-xl">
                {Math.round(point.rule).toLocaleString()}×{" "}
                <span className="text-noise text-base">
                  vs {Math.round(point.hold).toLocaleString()}×
                </span>
              </p>
            </div>
          </div>
        </div>

        <p className="data text-muted-foreground/70 mt-6 max-w-2xl text-[0.68rem] leading-relaxed">
          Illustrative curves generated by code, not a historical backtest or investment result. The sample rule is programmed to avoid part of each loss. Real testing needs historical fund and benchmark data, fees, taxes, a fixed universe, and rules set before testing. Past performance does not indicate future results.
        </p>
      </div>
    </section>
  );
}
